name: sharesyncapp
description: "P2P file transfer app using WebRTC."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_webrtc: ^0.12.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  dio: ^5.7.0
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.2
  wakelock_plus: ^1.2.8
  google_fonts: ^6.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
