// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdaMlf84rlFZXUhCI9KoCF1p9dyc-61I',
    appId: '1:497463857878:web:0733c03507c9f3e40eef77',
    messagingSenderId: '497463857878',
    projectId: 'sharesync-56711',
    authDomain: 'sharesync-56711.firebaseapp.com',
    storageBucket: 'sharesync-56711.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fO7NIwD_fMZRoCMBpfw_Oo_5YOAVJOk',
    appId: '1:497463857878:android:67f8002c4280e90e0eef77',
    messagingSenderId: '497463857878',
    projectId: 'sharesync-56711',
    storageBucket: 'sharesync-56711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7jG6yTXQ9yqPzqy3luSCFHbti3m4-7U',
    appId: '1:497463857878:ios:d5235da6606a1a640eef77',
    messagingSenderId: '497463857878',
    projectId: 'sharesync-56711',
    storageBucket: 'sharesync-56711.firebasestorage.app',
    iosBundleId: 'com.example.sharesyncapp',
  );
}
